#pragma once

#include <glib.h>

typedef enum {
    UI_LANGUAGE_ZH,
    UI_LANGUAGE_EN,
    UI_LANGUAGE_KO,
    UI_LANGUAGE_JA,
    UI_LANGUAGE_ES,
    UI_LANGUAGE_COUNT,
} UiLanguage;

typedef enum {
    UI_TEXT_LANGUAGE,
    UI_TEXT_NEW_PROJECT,
    UI_TEXT_NEW_TAB,
    UI_TEXT_RIGHT_TERMINAL,
    UI_TEXT_BELOW_TERMINAL,
    UI_TEXT_CLOSE_PANE,
    UI_TEXT_ZOOM_RESTORE,
    UI_TEXT_ALL_ACTIONS,
    UI_TEXT_CHOOSE_PROJECT_FOLDER,
    UI_TEXT_CREATE_WORKSPACE,
    UI_TEXT_CANCEL,
    UI_TEXT_NEW_WORKSPACE,
    UI_TEXT_SEARCH_WORKSPACES,
    UI_TEXT_CHAT_HISTORY,
    UI_TEXT_REFRESH_CHATS,
    UI_TEXT_RENAME_CHAT,
    UI_TEXT_EMPTY_CHATS,
    UI_TEXT_UNTITLED_CLAUDE,
    UI_TEXT_UNTITLED_CODEX,
    UI_TEXT_NOW,
    UI_TEXT_MINUTES_AGO,
    UI_TEXT_HOURS_AGO,
    UI_TEXT_DAYS_AGO,
    UI_TEXT_CLOSE_TAB_HEADING,
    UI_TEXT_CLOSE_TAB_BODY,
    UI_TEXT_CLOSE_TAB_CONFIRM,
    UI_TEXT_CLOSE_PANE_HEADING,
    UI_TEXT_CLOSE_PANE_BODY,
    UI_TEXT_CLOSE_PANE_CONFIRM,
    UI_TEXT_CLOSE_WORKSPACE_HEADING,
    UI_TEXT_CLOSE_WORKSPACE_BODY,
    UI_TEXT_CLOSE_WORKSPACE_CONFIRM,
    UI_TEXT_QUIT_HEADING,
    UI_TEXT_QUIT_BODY,
    UI_TEXT_QUIT_CONFIRM,
    UI_TEXT_CONFIRM_CLOSE,
    UI_TEXT_CONFIRM,
    UI_TEXT_DONT_ASK_AGAIN,
    UI_TEXT_COUNT,
} UiTextKey;

UiLanguage ui_language_current(void);
void ui_language_set(UiLanguage language);
const char *ui_language_code(UiLanguage language);
const char *ui_language_display_name(UiLanguage language);
const char *ui_text(UiTextKey key);
